### ISSUE TITLE
设定的S应该通过什么函数获取

### ISSUE THREAD

**Issue by miaokela** [wheeliar/WindowsFormsAppforFanuc#2]
<img width="302" alt="image" src="https://github.com/wheeliar/WindowsFormsAppforFanuc/assets/30903265/305592f8-5715-4f52-b392-a5c7b521e19a">

**Comment by wheeliar** [comment]
我查了也没找到，但想了一下，实际的转速不就是设定的这个值吗？

**Comment by miaokela** [comment]
<img width="532" alt="image" src="https://github.com/wheeliar/WindowsFormsAppforFanuc/assets/30903265/c8a3ae33-a4aa-4d68-94b5-e453326fe9c6">我设定的转速是3000，实际是1650/分，应该不是同一个吧？

**Comment by wheeliar** [comment]
设定转速*主轴倍率=实际转速，你看看你的主轴倍率是不是100%。

**Comment by miaokela** [comment]
<img width="573" alt="image" src="https://github.com/wheeliar/WindowsFormsAppforFanuc/assets/30903265/4c133995-067e-4939-8e64-7bf984a7d206">
原来还有进给倍率跟主轴倍率，但是这个主轴倍率100%还差了一倍，中间是不是还存在什么参数？

**Comment by wheeliar** [comment]
应该没有什么影响的了，程序跑起来也是一直都差一倍吗？

**Comment by miaokela** [comment]
对的，差一倍，这个是虚拟机上的数据，到现场还有一个怪现象，就是所有数据包括进给、主轴转速、绝对位移所有数值从cnc读出来都比机床的数据大10倍，单位都是一样的

**Comment by wheeliar** [comment]
你试试用其他人写的软件测试下读取正不正常。hslcommunicationdemo试试。

**Comment by miaokela** [comment]
你读过这俩开关的数据么
<img width="209" alt="image" src="https://github.com/wheeliar/WindowsFormsAppforFanuc/assets/30903265/0dfad867-6fa4-4dd8-96e1-02077021d481">
需要从PMC中读取，主轴倍率跟进给倍率的地址是编程人员设定的还是固定不变的

**Comment by miaokela** [comment]
我的理解是PMC中有一个固定的进给倍率、主轴倍率的PLC地址，编程人员在编代码的时候可以编入对应的倍率数据，操作人员也可以通过Sub Panel手动调整进给倍率和主轴倍率，是不是这个意思

**Comment by wheeliar** [comment]
G30就是pmc中主轴倍率的信号，你在面板上手动调整倍率开关这个，就可以读取到G30的值。

**Comment by miaokela** [comment]
完美解决 蟹蟹
